---
name: verify

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bufbuild/buf-setup-action@v1
      - run: buf lint .

  hadolint-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: dockerfiles/Dockerfile.cli
  
  hadolint-exporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: dockerfiles/Dockerfile.exporter

  hadolint-gc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: dockerfiles/Dockerfile.gc

  hadolint-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: dockerfiles/Dockerfile.manager

  hadolint-migrator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: dockerfiles/Dockerfile.migrator

  hadolint-publisher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: dockerfiles/Dockerfile.publisher

  hadolint-seeder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: dockerfiles/Dockerfile.seeder

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: articulate/actions-markdownlint@v1

  golangci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
      - name: Install dependencies
        run: go mod download
      - name: Install protoc-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go@latest
      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Generate the code
        run: go generate -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          only-new-issues: false
          working-directory: .

  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
      - name: Install dependencies
        run: go mod download
      - name: Install protoc-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go@latest
      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Generate the code
        run: go generate -v ./...
      - name: Test with the Go CLI
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
      - name: Install dependencies
        run: go mod download
      - name: Install protoc-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go@latest
      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Generate the code
        run: go generate -v ./...
      - name: Build project against .goreleaser.yaml
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: build --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build cli container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.cli
          platforms: amd64
          push: false
          outputs: type=image,name=ghcr.io/${{ github.repository }}/cli,annotation-index.org.opencontainers.image.description=${{ github.repository }}
      - name: Build exporter container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.exporter
          platforms: amd64
          push: false
          outputs: type=image,name=ghcr.io/${{ github.repository }}/exporter,annotation-index.org.opencontainers.image.description=${{ github.repository }}
      - name: Build gc container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.gc
          platforms: amd64
          push: false
          outputs: type=image,name=ghcr.io/${{ github.repository }}/gc,annotation-index.org.opencontainers.image.description=${{ github.repository }}
      - name: Build manager container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.manager
          platforms: amd64
          push: false
          outputs: type=image,name=ghcr.io/${{ github.repository }}/manager,annotation-index.org.opencontainers.image.description=${{ github.repository }}
      - name: Build migrator container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.migrator
          platforms: amd64
          push: false
          outputs: type=image,name=ghcr.io/${{ github.repository }}/migrator,annotation-index.org.opencontainers.image.description=${{ github.repository }}
      - name: Build publisher container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.publisher
          platforms: amd64
          push: false
          outputs: type=image,name=ghcr.io/${{ github.repository }}/publisher,annotation-index.org.opencontainers.image.description=${{ github.repository }}
      - name: Build seeder container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.seeder
          platforms: amd64
          push: false
          outputs: type=image,name=ghcr.io/${{ github.repository }}/seeder,annotation-index.org.opencontainers.image.description=${{ github.repository }}
